[env]
"CRATE_HEAP_SIZE" = "4g"

[settings]
"bootstrap.memory_lock" = true
"indices.breaker.query.limit" = "85%"
"cluster.name" = "cr8"
"node.name" = "bench1"
"stats.enabled" = true
"logger._root" = "ERROR"
"logger.http" = "INFO"
