[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = "select * from uservisits where duration in (?, ?, ?, ?, ?)"
iterations = 1000
args = [1, 2, 3, 4, 5]

[teardown]
statements = ["drop table uservisits"]
