[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00001*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00002*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00003*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00004*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00005*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = '''select distinct "cCode" from uservisits limit 20'''
concurrency = 15
iterations = 100

[[queries]]
statement = '''select distinct "searchWord" from uservisits limit 20'''
concurrency = 15
iterations = 100

[teardown]
statements = ["drop table uservisits"]
