[env]
"CRATE_HEAP_SIZE" = "4g"

[settings]
"bootstrap.mlockall" = true
"cluster.name" = "cr8"
"node.name" = "bench1"
"stats.enabled" = true
"indices.store.throttle.max_bytes_per_sec" = "100mb"
"logger._root" = "ERROR"
"logger.http" = "INFO"
