versions = [
    "latest-nightly"
]

configurations = [
    "default.toml"
]

specs = [
    "../specs/any.py",
    "../specs/in_numeric.toml",
    "../specs/in_string.toml",
    "../specs/count.toml",
    "../specs/group_by.toml",
    "../specs/like.toml",
    "../specs/joins.toml",
    "../specs/insert_single.toml",
    "../specs/insert_bulk.py",
    "../specs/delete_single.py",
    "../specs/delete_bulk.py",
    "../specs/generated_columns.toml",
    "../specs/create_partitions.py",
    "../specs/information_schema.py",
    "../specs/update_single.py",
    "../specs/update_bulk.py",
]
